---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-transfer-deployment
spec:
  selector:
    matchLabels:
      app: msg-transfer 
  # replicas: 12 
  replicas: 3
  template:
    metadata:
      labels:
        app: msg-transfer
    spec:
      containers:
      - name: msg-transfer
        image: truongpx396/openim-dev-msg_transfer:bdfd5717-69
        # command: ["./open_im_msg_transfer"]
        # args: ["--prometheus_port", "21400"]
        imagePullPolicy: Always
        ports:
        - name: prom-port
          containerPort: 21400
        volumeMounts:
          - name: config
            mountPath: /openim/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          # requests:
          #   memory: "512Mi"
          #   cpu: 300m
          requests:
            cpu: 70m
            memory: 60Mi
          limits:
            cpu: 180m
            memory: "100Mi"
            
            # memory: "1024Mi"
            # cpu: 600m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
            - configMap:
                name: notification
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - msg-transfer
              topologyKey: kubernetes.io/hostname
  strategy:
    type: RollingUpdate 
---
apiVersion: v1
kind: Service
metadata:
  name: msg-transfer
spec:
  ports:
    - name: msg-transfer-prom-port
      protocol: TCP
      port: 21400
      targetPort: prom-port
  selector:
    app: msg-transfer
  type: ClusterIP  
