---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-deployment
spec:
  selector:
    matchLabels:
      app: friend
  replicas: 3 
  template:
    metadata:
      labels:
        app: friend 
    spec:
      containers:
      - name: rpc-friend
        image: truongpx396/openim-dev-rpc_friend:611a3585-58
        imagePullPolicy: Always
        # command: ["./open_im_friend"]
        # args: ["--port", "10120", "--prometheus_port","20120"]
        ports:
        - containerPort: 10120
          name: friend-port
        - containerPort: 20120
          name: prom-port  
        # readinessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:10120"]
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:10120"]
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /openim/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          # requests:
          #   memory: "256Mi"
          #   cpu: 150m
          requests:
            cpu: 70m
            memory: 60Mi
          limits:
            cpu: 100m
            memory: "80Mi"
            # memory: "512Mi"
            # cpu: 300m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
            - configMap:
                name: notification
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - friend
              topologyKey: kubernetes.io/hostname
  strategy:
    type: RollingUpdate 
---
apiVersion: v1
kind: Service
metadata:
  name: friend
spec:
  ports:
    - name: friend-svc-port
      protocol: TCP
      port: 10120
      targetPort: friend-port
    - name: friend-prom-port
      protocol: TCP
      port: 20120
      targetPort: prom-port
  selector:
    app: friend
  type: ClusterIP  
