
apiVersion: v1
kind: Service
metadata:
  name: test-mysql-svc
spec:
  ports:
  - name: mysql
    port: 30100
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: openim-mysql
    app.kubernetes.io/name: mysql
  type: NodePort