---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-deployment
spec:
  selector:
    matchLabels:
      app: third 
  replicas: 3 
  template:
    metadata:
      labels:
        app: third
    spec:
      containers:
      - name: rpc-third
        image: truongpx396/openim-dev-rpc_third:98c15b5c-54
        imagePullPolicy: Always
        # command: ["./open_im_third"]
        # args: ["--port", "10200", "--prometheus_port", "20170"]
        ports:
        - containerPort: 10190
          name: third-port
        # readinessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:10200"]
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:10200"]
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /openim/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          # requests:
          #   memory: "512Mi"
          #   cpu: 300m
          requests:
            cpu: 70m
            memory: 60Mi
          limits:
            cpu: 100m
            memory: "80Mi"
            # memory: "1024Mi"
            # cpu: 600m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
            - configMap:
                name: notification
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - third
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate 

---
apiVersion: v1
kind: Service
metadata:
  name: third
spec:
  ports:
    - name: third-svc-port
      protocol: TCP
      port: 10190
      targetPort: third-port
    # - name: third-prom-port
    #   protocol: TCP
    #   port: 20200
    #   targetPort: third-prom-port
  selector:
    app: third
  type: ClusterIP  
