---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation-deployment
spec:
  selector:
    matchLabels:
      app: conversation
  replicas: 3
  template:
    metadata:
      labels:
        app: conversation
    spec:
      containers:
        - name: rpc-conversation
          image: truongpx396/openim-dev-rpc_conversation:5fcf641c-36
          imagePullPolicy: Always
          # command: ["./open_im_conversation"]
          # args: ["--port", "10230", "--prometheus_port","20230"]
          ports:
            - containerPort: 10230
              name: con-port
            - containerPort: 20230
              name: con-prom-port
          # readinessProbe:
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:10230"]
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:10230"]
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /openim/config
              readOnly: true
          env:
            - name: CONFIG_NAME
              value: "/Open-IM-Server"
          resources:
            # requests:
            #   memory: "256Mi"
            #   cpu: 150m
            requests:
              cpu: 70m
              memory: 100Mi
            limits:
              memory: "150Mi"
              cpu: 100m
              # memory: "512Mi"
              # cpu: 300m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
            - configMap:
                name: notification
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - conversation
              topologyKey: kubernetes.io/hostname
  strategy:
    type: RollingUpdate 
---
apiVersion: v1
kind: Service
metadata:
  name: conversation
spec:
  ports:
    - name: conversation-svc-port
      protocol: TCP
      port: 10230
      targetPort: con-port
    - name: conversation-prom-port
      protocol: TCP
      port: 20230
      targetPort: con-prom-port
  selector:
    app: conversation
  type: ClusterIP  
