---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3 
  template:
    metadata:
      labels:
        app: api 
    spec:
      containers:
      - name: api
        image: truongpx396/openim-dev-api:355074f8-59
        imagePullPolicy: Always
        ports:
        - containerPort: 10002
          name: api-port
        volumeMounts:
          - name: config
            mountPath: /openim/config
            readOnly: true
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 10002
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 10002
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          requests:
            cpu: 50m
            memory: "60Mi"
            # memory: "512Mi"
            # cpu: 300m
          limits:
            cpu: 80m
            memory: "80Mi"
            # memory: "1024Mi"
            # cpu: 600m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
            - configMap:
                name: notification
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - name: api-svc-port
      protocol: TCP
      port: 10002
      targetPort: api-port
  selector:
    app: api
  type: ClusterIP  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-deployment
spec:
  selector:
    matchLabels:
      app: busy
  replicas: 1
  template:
    metadata:
      labels:
        app: busy 
    spec:
      containers:
      - name: test-projected-volume
        image: busybox:1.28
        args:
        - sleep
        - "86400"
        volumeMounts:
          - name: config
            mountPath: /openim/config
            readOnly: true
        resources:
          requests:
            memory: "100Mi"
            cpu: 70m
            # memory: "512Mi"
            # cpu: 300m
          limits:
            memory: "250Mi"
            cpu: 100m
            # memory: "1024Mi"
            # cpu: 600m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
            - configMap:
                name: notification
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-mysql-deployment
spec:
  selector:
    matchLabels:
      app: test-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: test-mysql
    spec:
      containers:
      - name: test-msql
        image: bitnami/mysql:8.2.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: openIM123
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: openIM123
          - name: MYSQL_DATABASE
            value: openIM_v3
        resources:
          requests:
            memory: "100Mi"
            cpu: 70m
            # memory: "512Mi"
            # cpu: 300m
          limits:
            memory: "250Mi"
            cpu: 100m
            # memory: "1024Mi"
            # cpu: 600m
---
apiVersion: v1
kind: Service
metadata:
  name: test-mysql
spec:
  ports:
    - name: test-mysql
      protocol: TCP
      port: 3306
      targetPort: mysql
  selector:
    app: test-mysql
  type: ClusterIP  
     