---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: user 
  replicas: 3 
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: rpc-user
        image: truongpx396/openim-dev-rpc_user:37405b73-65
        imagePullPolicy: Always
        # command: ["./open_im_user"]
        # args: ["--port", "10110"]
        ports:
        - containerPort: 10110
          name: user-port
        - containerPort: 20110
          name: user-prom-port
        # readinessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:10110"]
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:10110"]
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /openim/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          # requests:
          #   memory: "256Mi"
          #   cpu: 150m
          requests:
            cpu: 70m
            memory: 60Mi
          limits:
            cpu: 100m
            memory: "80Mi"
            
            # memory: "512Mi"
            # cpu: 300m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
            - configMap:
                name: notification
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - user
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate 

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
    - name: user-svc-port
      protocol: TCP
      port: 10110
      targetPort: user-port
    - name: user-prom-port
      protocol: TCP
      port: 20110
      targetPort: user-prom-port
  selector:
    app: user
  type: ClusterIP  
