---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-api-admin-deployment
spec:
  selector:
    matchLabels:
      app: management-api-admin
  replicas: 1 
  template:
    metadata:
      labels:
        app: management-api-admin
    spec:
      containers:
      - name: management-api-admin
        image: truongpx396/openim-mgmt-dev-api-admin:6746fda-6
        imagePullPolicy: Always
        ports:
        - containerPort: 10009
          name: api-admin-port
        volumeMounts:
          - name: config
            mountPath: /openim/openim-chat/config
            readOnly: true
        resources:
          requests:
            memory: "50Mi"
            cpu: 30m
          limits:
            memory: "100Mi"
            cpu: 70m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - management-api-admin
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: management-api-admin
spec:
  ports:
    - name: api-admin-svc-port
      protocol: TCP
      port: 10009
      targetPort: api-admin-port
  selector:
    app: management-api-admin
  type: ClusterIP  